# Generated by Django 4.1.6 on 2024-02-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="measurement_unit",
            field=models.CharField(
                choices=[
                    ("g", "gram"),
                    ("kg", "kilogram"),
                    ("l", "litr"),
                    ("ml", "mililitr"),
                    ("szt.", "sztuka"),
                    ("łyżeczka", "łyżeczka"),
                    ("łyżka", "łyżka"),
                    ("szkl.", "szklanka"),
                    ("mg", "miligram"),
                ],
                default="szt.",
                max_length=10,
            ),
        ),
    ]
