# Generated by Django 4.1.6 on 2024-02-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_recipeingredient_calories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="grams_per_unit",
            field=models.FloatField(
                blank=True, null=True, verbose_name="grams per unit"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="other_measurement_unit",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="other measurement unit",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="price_per_hundred_gram",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                max_digits=5,
                verbose_name="price per 100 gram",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="price_per_unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="price per unit",
            ),
        ),
    ]
