# Generated by Django 5.0.1 on 2024-02-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_alter_recipeingredient_quantity_grams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="calories",
            field=models.FloatField(blank=True, null=True, verbose_name="calories"),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="other_unit",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="other unit"
            ),
        ),
    ]
