# Generated by Django 5.0.1 on 2024-02-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0009_alter_recipeingredient_calories_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="price_per_unit",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="calories",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="other_unit",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="calories_per_hundred_gram",
            field=models.FloatField(default=300, verbose_name="calories per 100 gram"),
        ),
    ]
