# Generated by Django 5.0.1 on 2024-02-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_remove_ingredient_price_per_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fruit", "Fruit"),
                    ("vegetables", "Vegetables"),
                    ("bread", "Bread"),
                    ("dairy", "Dairy"),
                    ("meat", "Meat"),
                    ("fish", "Fish"),
                    ("flour", "Flour"),
                    ("spices", "Spices"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="calories_per_hundred_gram",
            field=models.FloatField(verbose_name="calories per 100 gram"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="price_per_hundred_gram",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="price per 100 gram",
            ),
        ),
    ]
