# Generated by Django 5.0.2 on 2024-02-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_ingredient_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fruit", "Fruit"),
                    ("vegetables", "Vegetables"),
                    ("bread", "Bread"),
                    ("dairy", "Dairy"),
                    ("meat", "Meat"),
                    ("fish", "Fish"),
                    ("flour", "Flour"),
                    ("tinned", "Tinned"),
                    ("spices", "Spices"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
                verbose_name="category",
            ),
        ),
    ]
