# Generated by Django 5.0.1 on 2024-02-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_plan_planday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="days",
        ),
    ]
