# Generated by Django 5.0.1 on 2024-02-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_remove_plan_days"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="planday",
            unique_together={("plan", "day")},
        ),
    ]
